language : node_js
node_js :
 - stable
install:
 - yarn install
script:
 - yarn build
 - yarn cover
deploy:
  provider: npm
  email: "tylertracy1999@gmail.com"
  api_key: "$NPM_AUTH"
  on:
    branch: master